// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Products.API.DbContexts;

#nullable disable

namespace Products.API.Migrations
{
    [DbContext(typeof(ProductInfoContext))]
    [Migration("20231023141238_ModelUpdates")]
    partial class ModelUpdates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Products.API.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("longtext");

                    b.Property<string>("Code")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("InventoryStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "bamboo-watch.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Bamboo Watch",
                            Price = 65m,
                            Quantity = 24,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1001,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "black-watch.jpg",
                            InventoryStatus = "SIN STOCK",
                            Name = "Black Watch",
                            Price = 72m,
                            Quantity = 61,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1002,
                            Category = "Fitness",
                            Description = "Product Description",
                            Image = "blue-band.jpg",
                            InventoryStatus = "STOCK BAJO",
                            Name = "Blue Band",
                            Price = 79m,
                            Quantity = 2,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1003,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "blue-t-shirt.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Blue T-Shirt",
                            Price = 29m,
                            Quantity = 25,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1004,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "bracelet.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Bracelet",
                            Price = 15m,
                            Quantity = 73,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1005,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "brown-purse.jpg",
                            InventoryStatus = "SIN STOCK",
                            Name = "Brown Purse",
                            Price = 120m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1006,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "chakra-bracelet.jpg",
                            InventoryStatus = "STOCK BAJO",
                            Name = "Chakra Bracelet",
                            Price = 32m,
                            Quantity = 5,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1007,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "galaxy-earrings.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Galaxy Earrings",
                            Price = 34m,
                            Quantity = 23,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1008,
                            Category = "Electronica",
                            Description = "Product Description",
                            Image = "game-controller.jpg",
                            InventoryStatus = "STOCK BAJO",
                            Name = "Game Controller",
                            Price = 99m,
                            Quantity = 2,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1009,
                            Category = "Electronica",
                            Description = "Product Description",
                            Image = "gaming-set.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Gaming Set",
                            Price = 299m,
                            Quantity = 63,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1010,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "gold-phone-case.jpg",
                            InventoryStatus = "SIN STOCK",
                            Name = "Gold Phone Case",
                            Price = 24m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1011,
                            Category = "Electronica",
                            Description = "Product Description",
                            Image = "green-earbuds.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Green Earbuds",
                            Price = 89m,
                            Quantity = 23,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1012,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "green-t-shirt.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Green T-Shirt",
                            Price = 49m,
                            Quantity = 74,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1013,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "grey-t-shirt.jpg",
                            InventoryStatus = "SIN STOCK",
                            Name = "Grey T-Shirt",
                            Price = 48m,
                            Quantity = 0,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1014,
                            Category = "Electronica",
                            Description = "Product Description",
                            Image = "headphones.jpg",
                            InventoryStatus = "STOCK BAJO",
                            Name = "Headphones",
                            Price = 175m,
                            Quantity = 8,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1015,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "light-green-t-shirt.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Light Green T-Shirt",
                            Price = 49m,
                            Quantity = 34,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1016,
                            Category = "Fitness",
                            Description = "Product Description",
                            Image = "lime-band.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Lime Band",
                            Price = 79m,
                            Quantity = 12,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1017,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "mini-speakers.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Mini Speakers",
                            Price = 85m,
                            Quantity = 42,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1018,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "painted-phone-case.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Painted Phone Case",
                            Price = 56m,
                            Quantity = 41,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1019,
                            Category = "Fitness",
                            Description = "Product Description",
                            Image = "pink-band.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Pink Band",
                            Price = 79m,
                            Quantity = 63,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1020,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "pink-purse.jpg",
                            InventoryStatus = "SIN STOCK",
                            Name = "Pink Purse",
                            Price = 110m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1021,
                            Category = "Fitness",
                            Description = "Product Description",
                            Image = "purple-band.jpg",
                            InventoryStatus = "STOCK BAJO",
                            Name = "Purple Band",
                            Price = 79m,
                            Quantity = 6,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1022,
                            Category = "Accesorios",
                            Description = "Product Description",
                            Image = "purple-gemstone-necklace.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Purple Gemstone Necklace",
                            Price = 45m,
                            Quantity = 62,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1023,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "purple-t-shirt.jpg",
                            InventoryStatus = "STOCK BAJO",
                            Name = "Purple T-Shirt",
                            Price = 49m,
                            Quantity = 2,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1024,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "shoes.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Shoes",
                            Price = 64m,
                            Quantity = 0,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1025,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "sneakers.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Sneakers",
                            Price = 78m,
                            Quantity = 52,
                            Rating = 4
                        },
                        new
                        {
                            Id = 1026,
                            Category = "Vestimenta",
                            Description = "Product Description",
                            Image = "teal-t-shirt.jpg",
                            InventoryStatus = "STOCK BAJO",
                            Name = "Teal T-Shirt",
                            Price = 49m,
                            Quantity = 3,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1027,
                            Category = "Electronica",
                            Description = "Product Description",
                            Image = "yellow-earbuds.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Yellow Earbuds",
                            Price = 89m,
                            Quantity = 35,
                            Rating = 3
                        },
                        new
                        {
                            Id = 1028,
                            Category = "Fitness",
                            Description = "Product Description",
                            Image = "yoga-mat.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Yoga Mat",
                            Price = 20m,
                            Quantity = 15,
                            Rating = 5
                        },
                        new
                        {
                            Id = 1029,
                            Category = "Fitness",
                            Description = "Product Description",
                            Image = "yoga-set.jpg",
                            InventoryStatus = "EN STOCK",
                            Name = "Yoga Set",
                            Price = 20m,
                            Quantity = 25,
                            Rating = 8
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
